apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    name: my1stpod
spec:
  containers:
  - name: nginxcontainer
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80